[build]
  # Build command for your frontend
  command = "npm run build:frontend"
  
  # Directory where the built files will be located
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"

# Redirect rules for React Router (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you'll set these in Netlify dashboard)
# NEXT_PUBLIC_API_URL = "https://your-backend-url.com"
